/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["run_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/offcuts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Offcuts */
        get: operations["list_offcuts_inventory_offcuts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Save Project */
        post: operations["save_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/costing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Costing Config */
        get: operations["get_costing_config_config_costing_get"];
        /** Put Costing Config */
        put: operations["put_costing_config_config_costing_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CostDTO */
        CostDTO: {
            /** Material Placas */
            material_placas: number;
            /** Material Retazos */
            material_retazos: number;
            /** Tapacanto */
            tapacanto: number;
            /** Tiempo Cnc */
            tiempo_cnc: number;
            /** Mano Obra */
            mano_obra: number;
            /** Herrajes */
            herrajes: number;
            /** Margen */
            margen: number;
            /** Subtotal */
            subtotal: number;
            /** Total */
            total: number;
            /** Placas Nuevas */
            placas_nuevas: number;
            /** Retazos Consumidos */
            retazos_consumidos: number;
            /** Metros Tapacanto */
            metros_tapacanto: number;
            /** Minutos Cnc */
            minutos_cnc: number;
            /** Horas Mo */
            horas_mo: number;
        };
        /** CostingConfig */
        CostingConfig: {
            /** Precio Placa Mdf18 */
            precio_placa_mdf18: number;
            /** Factor Valor Retazo */
            factor_valor_retazo: number;
            /** Precio Tapacanto M */
            precio_tapacanto_m: number;
            /** Costo Hora Cnc */
            costo_hora_cnc: number;
            /** Velocidad Corte Mm Min */
            velocidad_corte_mm_min: number;
            /** Costo Hora Mo */
            costo_hora_mo: number;
            /** Horas Mo Default */
            horas_mo_default: number;
            /** Margen */
            margen: number;
            /** Kerf Mm */
            kerf_mm: number;
        };
        /** FurnitureSpec */
        FurnitureSpec: {
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "cabinet" | "shelving";
            /** Ancho */
            ancho: number;
            /** Alto */
            alto: number;
            /** Profundidad */
            profundidad: number;
            /**
             * Espesor
             * @default 18
             */
            espesor: number;
            /**
             * Num Estantes
             * @default 1
             */
            num_estantes: number;
            /**
             * Con Fondo
             * @default true
             */
            con_fondo: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareItemDTO */
        HardwareItemDTO: {
            /** Nombre */
            nombre: string;
            /** Qty */
            qty: number;
            /** Precio Unit */
            precio_unit: number;
        };
        /** LayoutDTO */
        LayoutDTO: {
            /** Sheets Used */
            sheets_used: components["schemas"]["SheetUsageDTO"][];
            /** Unplaced */
            unplaced: components["schemas"]["PieceDTO"][];
            /** New Offcuts */
            new_offcuts: components["schemas"]["OffcutDTO"][];
            /** Efficiency */
            efficiency: number;
        };
        /** OffcutDTO */
        OffcutDTO: {
            /** Id */
            id: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** PieceDTO */
        PieceDTO: {
            /** Name */
            name: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Qty */
            qty: number;
            /** Grain Locked */
            grain_locked: boolean;
            /** Edged */
            edged: [
                boolean,
                boolean,
                boolean,
                boolean
            ];
        };
        /** PipelineRequest */
        PipelineRequest: {
            furniture: components["schemas"]["FurnitureSpec"];
            /**
             * Use Inventory
             * @default false
             */
            use_inventory: boolean;
            /** Horas Mo */
            horas_mo?: number | null;
            /** Herrajes */
            herrajes?: components["schemas"]["HardwareItemDTO"][];
            /**
             * Export Dxf
             * @default false
             */
            export_dxf: boolean;
        };
        /** PipelineResponse */
        PipelineResponse: {
            /** Pieces */
            pieces: components["schemas"]["PieceDTO"][];
            layout: components["schemas"]["LayoutDTO"];
            costo: components["schemas"]["CostDTO"];
            /** Dxf Path */
            dxf_path?: string | null;
            /** Warnings */
            warnings?: string[];
        };
        /** PlacedPieceDTO */
        PlacedPieceDTO: {
            /** Piece Name */
            piece_name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Rotated */
            rotated: boolean;
        };
        /** ProjectMeta */
        ProjectMeta: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Created At */
            created_at: string;
            /**
             * Furniture Tipo
             * @enum {string}
             */
            furniture_tipo: "cabinet" | "shelving";
            /** Ancho */
            ancho: number;
            /** Alto */
            alto: number;
            /** Profundidad */
            profundidad: number;
        };
        /** SaveProjectRequest */
        SaveProjectRequest: {
            /** Nombre */
            nombre: string;
            spec: components["schemas"]["FurnitureSpec"];
            result: components["schemas"]["PipelineResponse"];
        };
        /** SavedProject */
        SavedProject: {
            meta: components["schemas"]["ProjectMeta"];
            spec: components["schemas"]["FurnitureSpec"];
            result: components["schemas"]["PipelineResponse"];
        };
        /** SheetUsageDTO */
        SheetUsageDTO: {
            /** Sheet Id */
            sheet_id: string;
            /** Sheet Width */
            sheet_width: number;
            /** Sheet Height */
            sheet_height: number;
            /** Is Offcut */
            is_offcut: boolean;
            /** Placed */
            placed: components["schemas"]["PlacedPieceDTO"][];
            /** Efficiency */
            efficiency: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    run_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_offcuts_inventory_offcuts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMeta"][];
                };
            };
        };
    };
    save_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedProject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_costing_config_config_costing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostingConfig"];
                };
            };
        };
    };
    put_costing_config_config_costing_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CostingConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostingConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
